-- Demo script that I've used to populate the database with data.
INSERT INTO product_types (name, tax_rate) VALUES 
('Electronics', 0.10), 
('Clothing', 0.15), 
('Furniture', 0.20), 
('Beauty', 0.25), 
('Sporting Goods', 0.15), 
('Home Appliances', 0.20), 
('Books', 0.05),
('Toys', 0.10),
('Food', 0.10),
('Jewelry', 0.30),
('Office Supplies', 0.15),
('Pet Supplies', 0.10);

INSERT INTO products (name, price, product_type_id)
VALUES
  ('Samsung Galaxy S21', 899.99, (SELECT id FROM product_types WHERE name = 'Electronics')),
  ('Levi''s 501 Original Fit Jeans', 69.50, (SELECT id FROM product_types WHERE name = 'Clothing')),
  ('KitchenAid Artisan Stand Mixer', 499.99, (SELECT id FROM product_types WHERE name = 'Home Appliances')),
  ('The Great Gatsby by F. Scott Fitzgerald', 14.99, (SELECT id FROM product_types WHERE name = 'Books')),
  ('Nike Air Zoom Pegasus 38', 119.99, (SELECT id FROM product_types WHERE name = 'Sports Equipment')),
  ('L''Oreal Paris Voluminous Lash Paradise Mascara', 9.99, (SELECT id FROM product_types WHERE name = 'Beauty and Personal Care')),
  ('Ikea Billy Bookcase', 79.00, (SELECT id FROM product_types WHERE name = 'Furniture')),
  ('Lego Star Wars Millennium Falcon', 799.99, (SELECT id FROM product_types WHERE name = 'Toys and Games')),
  ('Starbucks Pike Place Roast Coffee', 12.99, (SELECT id FROM product_types WHERE name = 'Food and Beverages')),
  ('Sharpie Permanent Markers, Assorted Colors', 7.99, (SELECT id FROM product_types WHERE name = 'Office Supplies')),
  ('Blue Buffalo Wilderness Chicken Recipe', 59.99, (SELECT id FROM product_types WHERE name = 'Pet Supplies')),
  ('1/2 Carat T.W. Diamond 10K White Gold Stud Earrings', 399.99, (SELECT id FROM product_types WHERE name = 'Jewelry')),
  ('Meguiar''s Ultimate Liquid Wax', 24.99, (SELECT id FROM product_types WHERE name = 'Automotive')),
  ('Yamaha FG800 Acoustic Guitar', 199.99, (SELECT id FROM product_types WHERE name = 'Musical Instruments')),
  ('Samsung Galaxy S22', 899.99, (SELECT id FROM product_types WHERE name = 'Electronics')),
  ('Nike Air Max 270', 149.99, (SELECT id FROM product_types WHERE name = 'Clothing')),
  ('Breville Smart Oven', 249.99, (SELECT id FROM product_types WHERE name = 'Home Appliances')),
  ('The Great Gatsby', 12.99, (SELECT id FROM product_types WHERE name = 'Books')),
  ('Spalding NBA Basketball', 29.99, (SELECT id FROM product_types WHERE name = 'Sports Equipment')),
  ('LOreal Paris Shampoo', 9.99, (SELECT id FROM product_types WHERE name = 'Beauty and Personal Care')),
  ('Ikea Billy Bookcase', 99.99, (SELECT id FROM product_types WHERE name = 'Furniture')),
  ('Lego Star Wars Set', 59.99, (SELECT id FROM product_types WHERE name = 'Toys and Games')),
  ('Nescafe Instant Coffee', 8.99, (SELECT id FROM product_types WHERE name = 'Food and Beverages')),
  ('Staples Printer Paper', 4.99, (SELECT id FROM product_types WHERE name = 'Office Supplies')),
  ('Purina Cat Food', 19.99, (SELECT id FROM product_types WHERE name = 'Pet Supplies')),
  ('Diamond Stud Earrings', 1999.99, (SELECT id FROM product_types WHERE name = 'Jewelry')),
  ('Michelin Defender Tires', 99.99, (SELECT id FROM product_types WHERE name = 'Automotive')),
  ('Yamaha Acoustic Guitar', 299.99, (SELECT id FROM product_types WHERE name = 'Musical Instruments')),
  ('Apple iPad', 399.99, (SELECT id FROM product_types WHERE name = 'Electronics')),
  ('Adidas Ultraboost Shoes', 179.99, (SELECT id FROM product_types WHERE name = 'Clothing')),
  ('Vitamix Blender', 499.99, (SELECT id FROM product_types WHERE name = 'Home Appliances')),
  ('The Catcher in the Rye', 10.99, (SELECT id FROM product_types WHERE name = 'Books')),
  ('Wilson Tennis Racket', 59.99, (SELECT id FROM product_types WHERE name = 'Sports Equipment')),
  ('Head & Shoulders Shampoo', 7.99, (SELECT id FROM product_types WHERE name = 'Beauty and Personal Care')),
  ('Ikea Hemnes Dresser', 199.99, (SELECT id FROM product_types WHERE name = 'Furniture')),
  ('Nerf Gun', 19.99, (SELECT id FROM product_types WHERE name = 'Toys and Games')),
  ('Coca-Cola 12-Pack', 5.99, (SELECT id FROM product_types WHERE name = 'Food and Beverages')),
  ('Sharpie Permanent Markers', 8.99, (SELECT id FROM product_types WHERE name = 'Office Supplies')),
  ('Purina Dog Food', 24.99, (SELECT id FROM product_types WHERE name = 'Pet Supplies')),
  ('Pearl Necklace', 999.99, (SELECT id FROM product_types WHERE name = 'Jewelry')),
  ('Bridgestone Tires', 79.99, (SELECT id FROM product_types WHERE name = 'Automotive'));